### ISSUE TITLE
Make Prettification optional

### ISSUE THREAD

**Issue by JavaPerformance** [mjfryc/mjaron-tinyloki-java#14]
Hi, I have added the builder methods withPrettify() and withoutPrettify() to Labels (locally) as my labels value were being corrupted and I couldn't link between Loki and Tempo.

I tested and it would *seem* that Loki can now (v2.6.1) accept unprettified labels/values.

Do you think this is a good idea?

Paul.

**Comment by mjfryc** [comment]
Thank you for telling about this bug.

Here is the specification <https://prometheus.io/docs/concepts/data_model>:

> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.
> 
> Label values may contain any Unicode characters.
> 
> A label with an empty label value is considered equivalent to a label that does not exist.

So, I will fix it by prettifying label names only - label values will never be changed.

**Comment by mjfryc** [comment]
* Done. Uploaded to Maven Central with version `0.3.9`.
* It will be accessible after few hours.
* Now all label values are accepted (still name-value length limits matters).
